name: Windows Adoptium

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:


      - name: Install JDK
        run: |
          curl -o jdk.zip -L https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.2%2B8/OpenJDK17U-jdk_x64_windows_hotspot_17.0.2_8.zip
          unzip jdk.zip
          rm jdk.zip


      - uses: actions/checkout@v3

      - name: Maven Settings
        run: |
          cp adoptium-font-crash/src/setup/windows/toolchain.xml $HOME/.m2/toolchains.xml
          (Get-Content ~/.m2/toolchains.xml) -replace"<jdkHome>.*</jdkHome>", ("<jdkHome>"+[Environment]::GetEnvironmentVariable('JAVA_HOME')+"</jdkHome>") | Set-Content ~/.m2/toolchains.xml

      - name: Build with Maven
        run: cd adoptium-font-crash/ && mvn --batch-mode package 

      - name: Archive 
        uses: actions/upload-artifact@v3
        with:
          name: kit
          path: adoptium-font-crash/target/adoptium-font-crash-1.0-SNAPSHOT-distribution.zip
          retention-days: 2
